EXTEND_BOTTOM ~m#amber.bcs~ ~crossmodbg2/files/amber_xan/m#amber.baf~ EVALUATE_BUFFER
  
// interjections
OUTER_SET actual_joining_state    = (STATE_WHICH_SAYS 5023 IN ~amber/tra/%s/dialogs.tra~ FROM ~m#amber~)
OUTER_SET actual_kidnapping_state = (STATE_WHICH_SAYS 5207 IN ~amber/tra/%s/dialogs.tra~ FROM ~m#ambern~)

COMPILE EVALUATE_BUFFER  ~crossmodbg2/files/amber_xan/soa_interjections.d~
EXTEND_TOP ~o#xans.bcs~  ~crossmodbg2/files/amber_xan/o#xans.baf~ 