WITH_TRA ~coran/%s/O#CORANJ.tra~ BEGIN
  OUTER_SET strref1 = RESOLVE_STR_REF(@117)
  /* I only wish Khalid and Dynaheir had the same blessing. */
END
STRING_SET strref1 @5

WITH_TRA ~coran/%s/O#CORANJ.tra~ BEGIN
  OUTER_SET strref2 = RESOLVE_STR_REF(@125)
  /* Ah, yes... It is truly a waste how death grasps at youth and beauty. Dynaheir had both, and Khalid was a fine companion. */
END
STRING_SET strref2 @6